name: 'EddieHubCommunity labels Action'
description: 'Import open source issue labels standards'
inputs:
  github-token:
    description: 'GitHub token for repo'
    required: true
  owner-name:
    description: 'Owner name is user or organisation'
    required: true
  repository-name:
    description: 'GitHub repo name'
    required: true
runs:
  using: "composite"
  steps:
    - name: 'install dependency'
      run: npm install github-label-template
      shell: bash
    - name: 'delete existing labels'
      run: npx ghlbl -o ${{ inputs.owner-name }} -r ${{ inputs.repository-name }} -t ${{ inputs.github-token }} -d
      shell: bash
    - name: 'import labels from json file'
      run: npx ghlbl -o ${{ inputs.owner-name }} -r ${{ inputs.repository-name }} -t ${{ inputs.github-token }} -i ${{ github.action_path }}/labels.json
      shell: bash
